### PR TITLE
challenge 1 kristin abijaoude

### PR DESCRIPTION
**Pull request by kabijaoude**

### CODE REVIEW

**Review by ThogaruSathvik — CHANGES_REQUESTED** [review]
Kindly donot delete any files or modify any files in the templates folder. Please book an appointment with any one of the tutors if you have any queries or confusion in submitting the pull request or working on your assignments

**Review by ThogaruSathvik — CHANGES_REQUESTED** [review]
Book an appointment with tutor

Notes: files deleted in the templates folder

**Comment by kabijaoude** [comment]
I have already gone to a tutor for help.

**Comment by ThogaruSathvik** [comment]
> I have already gone to a tutor for help.

I still see an issue with the templates folder. A file got deleted. Kindly schedule an appointment

**Review by ThogaruSathvik — APPROVED** [review]

**Pull request merged**
