### PR TITLE
homework_1

### PR DESCRIPTION
**Pull request by said-arslan**

### CODE REVIEW

**Comment by said-arslan** [comment]
Hi there!

**Review by ThogaruSathvik — COMMENTED** [review]
please submit it to the submission branch

**Comment by said-arslan** [comment]
Hi Thogaru,

To be honest, I don't know exactly how to submit it to the submission branch. I just created SaidArslan.qmd document and saved it in "about" folder in the directory on my computer, then saved an image in "about/image" folder as well, and then did push and pull request. I don't know when and where to specify the submission branch to submit.
Could you give me instructions to do it?
Thanks.

**Comment by ThogaruSathvik** [comment]
Hi Said-Arslan , while submitting the pull request click on compare across forks and choose submission instars of template for the 601 fall 2022 and submit the pull  request . I have attached a screenshot for your reference. Let me know if you find any issue.

**Comment by said-arslan** [comment]
Hi Thogaru,

I couldn't open the screenshot you posted. I created new pull request after choosing submission branch. Please let me know if it worked.

Thank you.

**Comment by ThogaruSathvik** [comment]
yes you did it correctly now. Thank you

**Pull request closed without merging**
