### PR TITLE
Sarah M - Challenge 1 and updated About Me

### PR DESCRIPTION
**Pull request by sarahmcalpine**
I have too many commits and don't know how to remove them!

### CODE REVIEW

**Review by ThogaruSathvik — COMMENTED** [review]
I see two files for challenge1 can you please submit only one file. you can delete the other file and submit the pull request

**Review by ThogaruSathvik — CHANGES_REQUESTED** [review]
submit only one file for challenge 1

**Comment by sarahmcalpine** [comment]
@ThogaruSathvik I think I deleted them successfully--there should be just an update to by about page and now a challenge one with 920, yesterday's date, in the file name.

**Review by ThogaruSathvik — APPROVED** [review]

**Comment by sarahmcalpine** [comment]
Thank you! This does not seem like an easy role--I appreciate all your
effort and work!

**Comment by sarahmcalpine** [comment]
Hi! I’m not sure how to delete or remove a commit. Can you help with that process?

Sarah M

**Pull request merged**
