### PR TITLE
Submitting the homework2

### PR DESCRIPTION
**Pull request by Enagai-nagai**
Homework 2 Erika Nagai.
I used the package "qdapRegex"

### CODE REVIEW

**Review by ThogaruSathvik — COMMENTED** [review]
add your datasets to posts/_data folder and remove the images folder
raise the pull request again

**Comment by Enagai-nagai** [comment]
I dropped said folders

**Review by ThogaruSathvik — APPROVED** [review]

**Review by ThogaruSathvik — APPROVED** [review]

**Comment by Enagai-nagai** [comment]
Hello, I deleted the data and image folders this morning. Could you please
accept my request?
I want to receive the feedback on my work during the class.

2022年10月12日(水) 2:50 Sathvik Thogaru ***@***.***>:

**Comment by Enagai-nagai** [comment]
Thank you very much!
I sent another request because I changed the file repository. Could you
kindly accept the request again?

Best regards,
Erika

2022年10月12日(水) 18:06 Sathvik Thogaru ***@***.***>:

**Pull request merged**
