### PR TITLE
Challenge1_solutions Amer Abuhasan

### PR DESCRIPTION
**Pull request by aabuhasan**

### CODE REVIEW

**Review by ThogaruSathvik — CHANGES_REQUESTED** [review]
save the file as "firstLastName_challenge 1".qmd" and submit the pull request again

**Comment by aabuhasan** [comment]
I tried to do it, it wont let me select the new one.

**Review by ThogaruSathvik — CHANGES_REQUESTED** [review]
wrong file extension. Check the below example to name your file.

Ex: "FirstLastName_challenge1.qmd"

**Comment by aabuhasan** [comment]
UPDATE NAME OF FILE for challenge 1

**Review by ThogaruSathvik — CHANGES_REQUESTED** [review]
your submission for a challenge should be only one file. Delete the other file and raise the pull request again

**Review by ThogaruSathvik — APPROVED** [review]

**Pull request merged**
